import sqlite3
import pandas as pd, pybaseball as pyb, matplotlib.pyplot as plt, seaborn as sns, mlbgame as mlb


divisions = {
    "AL East": ["BOS", "NYY", "TBR", "TOR", "BAL"],
    "AL Central": ["CLE", "MIN", "KCR", "CHW", "DET"],
    "AL West": ["HOU", "LAA", "SEA", "TEX", "OAK"],
    "NL East": ["WSN", "MIA", "ATL", "NYM", "PHI"],
    "NL Central": ["CHC", "MIL", "STL", "PIT", "CIN"],
    "NL West": ["LAD", "ARI", "COL", "SDP", "SFG"],
}
teams = ['BOS',
         'NYY',
         'TBR',
         'KCR',
         'CHW',
         'BAL',
         'CLE',
         'MIN',
         'DET',
         'HOU',
         'LAA',
         'SEA',
         'TEX',
         'OAK',
         'WSN',
         'MIA',
         'ATL',
         'NYM',
         'PHI',
         'CHC',
         'MIL',
         'STL',
         'PIT',
         'CIN',
         'LAD',
         'ARI',
         'COL',
         'SDP',
         'SFG',
         'TOR']
team_colors = {
    "BOS": "#BD3039",
    "NYY": "#003087",
    "TBR": "#8FBCE6",
    "KCR": "#BD9B60",
    "CHW": "#27251F",
    "BAL": "#DF4601",
    "CLE": "#E31937",
    "MIN": "#002B5C",
    "DET": "#FA4616",
    "HOU": "#EB6E1F",
    "LAA": "#BA0021",
    "SEA": "#005C5C",
    "TEX": "#003278",
    "OAK": "#003831",
    "WSN": "#14225A",
    "MIA": "#FF6600",
    "ATL": "#13274F",
    "NYM": "#002D72",
    "PHI": "#E81828",
    "CHC": "#0E3386",
    "MIL": "#B6922E",
    "STL": "#C41E3A",
    "PIT": "#FDB827",
    "CIN": "#C6011F",
    "LAD": "#005A9C",
    "ARI": "#A71930",
    "COL": "#33006F",
    "SDP": "#002D62",
    "SFG": "#FD5A1E",
    "TOR": "#134A8E",
}

